name: pricesurge

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    networks:
      - pricesurge_network
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:5050
    networks:
      - pricesurge_network

networks:
  pricesurge_network:
    driver: bridge
